version: '3.9'

services:
  social_nginx:
    image: nginx:latest
    restart: always
    ports:
      - '8083:80'
    volumes:
      - ./../:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./../var/log/nginx:/var/log/nginx
    depends_on:
      - social_php
    networks:
      - pgnet

  social_db:
    container_name: social_db
    image: postgres:15
    command: "postgres -c config_file=/config/postgresql.conf"
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: smth
      POSTGRES_DB: social
      POSTGRES_USER: social
      PGDATA: "/data"
    ports:
      - "15432:5432"
    volumes:
      - ./pgmaster/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../var/temp.csv:/temp/temp.csv
      #- ./pgmaster/config:/config
      - social_pg_master:/data:rw
      - social_pg_backup:/postgres-wal-dir
    networks:
      - pgnet

  pgslave:
    container_name: pgslave
    image: postgres:15
    command: "postgres -c config_file=/config/postgresql.conf"
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: smth
      POSTGRES_USER: social
      PGDATA: "/data"
    ports:
      - "15434:5432"
    volumes:
      - ./pgslave/config:/config
      - social_pg_backup:/data:rw
    networks:
      - pgnet

  pgasyncslave:
    container_name: pgasyncslave
    image: postgres:15
    command: "postgres -c config_file=/config/postgresql.conf"
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: smth
      POSTGRES_USER: social
      PGDATA: "/data"
    ports:
      - "15435:5432"
    volumes:
      - ./pgasyncslave/config:/config
      - social_pg_backup:/data:rw
    networks:
      - pgnet

  social_php:
    build:
      context: ./php-fpm
      args:
        UID: ${UID}
        GID: ${GID}
    expose:
      - 9000
    restart: always
    volumes:
      - ./..:/usr/share/nginx/html
      - ./php-fpm/debug/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./php-fpm/debug/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    working_dir: /usr/share/nginx/html
    user: ${UID}:${GID}
    depends_on:
      - social_db
    networks:
      - pgnet

volumes:
  #social_db_data:
  social_pg_master:
  social_pg_backup:

networks:
  pgnet:
    name: pgnet
    external: true

